# HF model id: codellama/CodeLlama-7b-Instruct-hf
# Normalized by autotest/tools/normalize_model_configs.py

a100:
- model_type: chat
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    - kvint4
    - kvint8
  deps:
    transformers: 4.57.6
