repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        files: ^lmdeploy/
        args: ["--fix", "--exit-non-zero-on-fix"]
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--extend-ignore=E231', "--max-line-length=120"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--line-length=120"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-openmmlab
          - mdformat_frontmatter
          - linkify-it-py
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: ["--skip=third_party/*,*.ipynb,*.proto,src/turbomind/*,docker/Dockerfile_ascend*,docs/en/get_started/ascend/get_started.md,docs/zh_cn/get_started/ascend/get_started.md"]


  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        language_version: python3.10
        args: ["--in-place", "--wrap-descriptions", "120"]

  - repo: https://github.com/open-mmlab/pre-commit-hooks
    rev: v0.2.0
    hooks:
    -   id: check-copyright
        args: ["lmdeploy"]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v11.1.0
    hooks:
      - id: clang-format
        files: ^src/
        types_or: [c, c++, cuda]

exclude: |
  (?x)(
    ^cmake/.*\.patch$
  )
