#!/bin/sh

cmake -G Ninja .. \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -DCMAKE_INSTALL_PREFIX=./install \
    -DBUILD_MULTI_GPU=ON \
    -DBUILD_CUTLASS_MOE=OFF \
    -DBUILD_CUTLASS_MIXED_GEMM=OFF \
    -DCMAKE_CUDA_FLAGS="-lineinfo" \
    -DUSE_NVTX=ON
