model_path: /mnt/shared-storage-user/auto-eval-pipeline/qa-llm-cicd/model
resource_path: /mnt/shared-storage-user/auto-eval-pipeline/qa-llm-cicd/resource
log_path: /mnt/shared-storage-user/auto-eval-pipeline/qa-llm-cicd/log
eval_log_path: /mnt/shared-storage-user/auto-eval-pipeline/qa-llm-cicd/evaluation_report
benchmark_path: /mnt/shared-storage-user/auto-eval-pipeline/qa-llm-cicd/benchmark-reports
dataset_path: /mnt/shared-storage-user/auto-eval-pipeline/datasets/ShareGPT_V3_unfiltered_cleaned_split.json
env_tag: h200

tp_config:
    Intern-S1: 4
    Qwen3-235B-A22B: 8
    Qwen3-235B-A22B-FP8: 4
    Qwen3-30B-A3B: 2
    Qwen3-32B: 2
    gpt-oss-120b: 2
    gpt-oss-120b-BF16: 4
    gpt-oss-20b-BF16: 2
    DeepSeek-V3.1: 8

turbomind_chat_model:
    - internlm/Intern-S1
    - internlm/Intern-S1-mini
    - Qwen/Qwen3-0.6B-FP8
    - Qwen/Qwen3-1.7B-FP8
    - Qwen/Qwen3-4B-FP8
    - Qwen/Qwen3-8B-FP8
    - Qwen/Qwen3-14B-FP8
    - Qwen/Qwen3-235B-A22B
    - Qwen/Qwen3-235B-A22B-FP8
    - Qwen/Qwen3-30B-A3B
    - Qwen/Qwen3-30B-A3B-FP8
    - Qwen/Qwen3-32B
    - Qwen/Qwen3-32B-FP8
    - openai/gpt-oss-120b
    - openai/gpt-oss-20b
    - deepseek/DeepSeek-V3.1

pytorch_chat_model:
    - internlm/Intern-S1
    - internlm/Intern-S1-mini
    - Qwen/Qwen3-0.6B-FP8
    - Qwen/Qwen3-1.7B-FP8
    - Qwen/Qwen3-4B-FP8
    - Qwen/Qwen3-8B-FP8
    - Qwen/Qwen3-14B-FP8
    - Qwen/Qwen3-235B-A22B
    - Qwen/Qwen3-235B-A22B-FP8
    - Qwen/Qwen3-30B-A3B
    - Qwen/Qwen3-30B-A3B-FP8
    - Qwen/Qwen3-32B
    - Qwen/Qwen3-32B-FP8
    - unsloth/gpt-oss-120b-BF16
    - unsloth/gpt-oss-20b-BF16
    - deepseek/DeepSeek-V3.1

turbomind_vl_model:
    - internlm/Intern-S1
    - internlm/Intern-S1-mini

pytorch_vl_model:
    - internlm/Intern-S1
    - internlm/Intern-S1-mini

turbomind_base_model:
    - internlm/Intern-S1-mini
    - Qwen/Qwen3-4B-FP8
    - openai/gpt-oss-20b

pytorch_base_model:
    - internlm/Intern-S1-mini
    - Qwen/Qwen3-4B-FP8
    - unsloth/gpt-oss-20b-BF16

turbomind_quatization:
    no_awq:
        - internlm/Intern-S1
        - internlm/Intern-S1-mini
        - Qwen/Qwen3-0.6B-FP8
        - Qwen/Qwen3-1.7B-FP8
        - Qwen/Qwen3-4B-FP8
        - Qwen/Qwen3-8B-FP8
        - Qwen/Qwen3-14B-FP8
        - Qwen/Qwen3-235B-A22B
        - Qwen/Qwen3-235B-A22B-FP8
        - Qwen/Qwen3-30B-A3B
        - Qwen/Qwen3-30B-A3B-FP8
        - Qwen/Qwen3-32B
        - Qwen/Qwen3-32B-FP8
        - openai/gpt-oss-120b
        - openai/gpt-oss-20b
    gptq:
        - empty
    no_kvint4:
        - internlm/Intern-S1
        - internlm/Intern-S1-mini
        - Qwen/Qwen3-0.6B-FP8
        - Qwen/Qwen3-1.7B-FP8
        - Qwen/Qwen3-4B-FP8
        - Qwen/Qwen3-8B-FP8
        - Qwen/Qwen3-14B-FP8
        - Qwen/Qwen3-235B-A22B
        - Qwen/Qwen3-235B-A22B-FP8
        - Qwen/Qwen3-30B-A3B
        - Qwen/Qwen3-30B-A3B-FP8
        - Qwen/Qwen3-32B
        - Qwen/Qwen3-32B-FP8
        - openai/gpt-oss-120b
        - openai/gpt-oss-20b
    no_kvint8:
        - empty

pytorch_quatization:
    awq:
        - empty
    w8a8:
        - empty
    no_kvint4:
        - internlm/Intern-S1
        - internlm/Intern-S1-mini
        - Qwen/Qwen3-0.6B-FP8
        - Qwen/Qwen3-1.7B-FP8
        - Qwen/Qwen3-4B-FP8
        - Qwen/Qwen3-8B-FP8
        - Qwen/Qwen3-14B-FP8
        - Qwen/Qwen3-235B-A22B
        - Qwen/Qwen3-235B-A22B-FP8
        - Qwen/Qwen3-30B-A3B
        - Qwen/Qwen3-30B-A3B-FP8
        - Qwen/Qwen3-32B
        - Qwen/Qwen3-32B-FP8
    no_kvint8:
        - empty

longtext_model:
    - Qwen/Qwen3-30B-A3B

benchmark_model:
    - internlm/Intern-S1
    - internlm/Intern-S1-mini
    - meta-llama/Meta-Llama-3-1-8B-Instruct
    - meta-llama/Meta-Llama-3-1-70B-Instruct
    - Qwen/Qwen3-32B
    - Qwen/Qwen3-30B-A3B
    - Qwen/Qwen3-235B-A22B
    - Qwen/Qwen2.5-72B-Instruct
    - openai/gpt-oss-120b
    - openai/gpt-oss-20b
    - unsloth/gpt-oss-20b-BF16
    - unsloth/gpt-oss-120b-BF16


evaluate_model:
    - Qwen/Qwen3-0.6B-FP8
    - Qwen/Qwen3-1.7B-FP8
    - Qwen/Qwen3-4B-FP8
    - Qwen/Qwen3-8B-FP8
    - Qwen/Qwen3-14B-FP8
    - Qwen/Qwen3-32B
    - Qwen/Qwen3-32B-FP8
    - Qwen/Qwen3-30B-A3B
    - Qwen/Qwen3-30B-A3B-FP8
    - Qwen/Qwen3-235B-A22B
    - Qwen/Qwen3-235B-A22B-FP8
    - openai/gpt-oss-120b
    - openai/gpt-oss-20b
    - unsloth/gpt-oss-120b-BF16
    - unsloth/gpt-oss-20b-BF16
    - deepseek/DeepSeek-V3.1
