model_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/model
resource_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/resource
log_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/log
server_log_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/server_log
eval_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/evaluation_report
mllm_eval_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/mllm_evaluation_report
benchmark_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/benchmark_report
dataset_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/datasets/ShareGPT_V3_unfiltered_cleaned_split.json
prefix_dataset_path: /mnt/shared-storage-user/llmrazor-share/qa-llm-cicd/cicd-autotest/eval_resource/datasets/prefix_cache_test.json
env_tag: h
device: cuda

config:
    tp:
        Qwen/Qwen3-235B-A22B-Thinking-2507-FP8: 4
        Qwen/Qwen3-30B-A3B: 2
        openai/gpt-oss-120b: 2
        openai/gpt-oss-20b: 2
        unsloth/gpt-oss-20b-BF16: 2
        deepseek-ai/DeepSeek-V3.1: 8
        Qwen/Qwen3-30B-A3B-Base: 2
        Qwen/Qwen3-235B-A22B-Thinking-2507: 8
        OpenGVLab/InternVL3_5-38B: 2
        Qwen/Qwen3-VL-30B-A3B-Instruct: 2
        zai-org/GLM-5: 16
        Qwen/Qwen3.5-27B: 2
        Qwen/Qwen3.5-35B-A3B: 2
        Qwen/Qwen3.5-122B-A10B: 4
        meta-llama/Llama-4-Scout-17B-16E-Instruct: 4
        meta-llama/Meta-Llama-3.1-70B-Instruct: 4
        OpenGVLab/InternVL3-38B: 2
        Qwen/Qwen2.5-VL-32B-Instruct: 2
        deepseek-ai/DeepSeek-V2-Lite-Chat: 2
        mistralai/Mixtral-8x7B-Instruct-v0.1: 2
        OpenGVLab/InternVL3_5-30B-A3B: 2
        zai-org/GLM-4.7-Flash: 2
        google/gemma-3-27b-it: 2

    dp_ep:
        Qwen/Qwen3-235B-A22B-Thinking-2507:
            dp: 8
            ep: 8

    cp_tp:
        Qwen/Qwen3-235B-A22B-Thinking-2507:
            cp: 2
            tp: 8


turbomind_chat_model:
    tp:
        - meta-llama/Llama-3.2-1B-Instruct
        - meta-llama/Llama-3.2-3B-Instruct
        - meta-llama/Meta-Llama-3.1-8B-Instruct
        - meta-llama/Meta-Llama-3.1-70B-Instruct
        - meta-llama/Meta-Llama-3-8B-Instruct
        - internlm/internlm3-8b-instruct
        - internlm/internlm3-8b-instruct-awq
        - OpenGVLab/InternVL3-8B
        - OpenGVLab/InternVL3-38B
        - OpenGVLab/InternVL3_5-30B-A3B
        - Qwen/Qwen3-0.6B
        - Qwen/Qwen3-4B
        - Qwen/Qwen3-8B
        - Qwen/Qwen3-32B-FP8
        - Qwen/Qwen3-30B-A3B
        - Qwen/Qwen3-30B-A3B-FP8
        - Qwen/Qwen3-235B-A22B-Thinking-2507
        - Qwen/Qwen3-235B-A22B-Thinking-2507-FP8
        - Qwen/Qwen2.5-VL-7B-Instruct
        - Qwen/Qwen2.5-VL-32B-Instruct
        - Qwen/Qwen1.5-MoE-A2.7B-Chat
        - mistralai/Mixtral-8x7B-Instruct-v0.1
        - OpenGVLab/InternVL3_5-38B
        - deepseek-ai/DeepSeek-V2-Lite-Chat
        - THUDM/glm-4-9b-chat
        - openai/gpt-oss-120b
        - openai/gpt-oss-20b

    cp_tp:
        - Qwen/Qwen3-235B-A22B-Thinking-2507


pytorch_chat_model:
    tp:
        - meta-llama/Llama-4-Scout-17B-16E-Instruct
        - meta-llama/Llama-3.2-1B-Instruct
        - meta-llama/Llama-3.2-3B-Instruct
        - meta-llama/Meta-Llama-3.1-8B-Instruct
        - meta-llama/Meta-Llama-3.1-70B-Instruct
        - meta-llama/Meta-Llama-3-8B-Instruct
        - internlm/internlm3-8b-instruct
        - OpenGVLab/InternVL3-8B
        - OpenGVLab/InternVL3-38B
        - OpenGVLab/InternVL3_5-30B-A3B
        - Qwen/Qwen3-0.6B
        - Qwen/Qwen3-4B
        - Qwen/Qwen3-8B
        - Qwen/Qwen3-32B-FP8
        - Qwen/Qwen3-30B-A3B
        - Qwen/Qwen3-30B-A3B-FP8
        - Qwen/Qwen3-235B-A22B-Thinking-2507
        - Qwen/Qwen3-235B-A22B-Thinking-2507-FP8
        - Qwen/Qwen3-VL-8B-Instruct
        - Qwen/Qwen3-VL-30B-A3B-Instruct
        - THUDM/cogvlm-chat-hf
        - THUDM/cogvlm2-llama3-chinese-chat-19B
        - THUDM/glm-4v-9b
        - THUDM/glm-4-9b-chat
        - zai-org/GLM-4.7-Flash
        - microsoft/Phi-3.5-vision-instruct
        - microsoft/Phi-3-vision-128k-instruct
        - zai-org/GLM-5
        - Qwen/Qwen3.5-27B
        - Qwen/Qwen3.5-35B-A3B
        - Qwen/Qwen3.5-122B-A10B
        - deepseek-ai/DeepSeek-V3.1
        - unsloth/gpt-oss-20b-BF16
        - google/gemma-3-27b-it
        - OpenGVLab/InternVL3_5-38B

    dp_ep:
        - Qwen/Qwen3-235B-A22B-Thinking-2507

turbomind_vl_model:
    tp:
        - OpenGVLab/InternVL3-8B
        - OpenGVLab/InternVL3-38B
        - OpenGVLab/InternVL3_5-30B-A3B
        - Qwen/Qwen2.5-VL-7B-Instruct
        - Qwen/Qwen2.5-VL-32B-Instruct
        - OpenGVLab/InternVL3_5-38B

pytorch_vl_model:
    tp:
        - OpenGVLab/InternVL3-8B
        - OpenGVLab/InternVL3_5-30B-A3B
        - Qwen/Qwen3-VL-8B-Instruct
        - Qwen/Qwen3-VL-30B-A3B-Instruct
        - THUDM/cogvlm-chat-hf
        - THUDM/cogvlm2-llama3-chinese-chat-19B
        - THUDM/glm-4v-9b
        - microsoft/Phi-3-vision-128k-instruct
        - microsoft/Phi-3.5-vision-instruct
        - Qwen/Qwen3.5-27B
        - Qwen/Qwen3.5-35B-A3B
        - Qwen/Qwen3.5-122B-A10B
        - OpenGVLab/InternVL3_5-38B


turbomind_base_model:
    tp:
        - Qwen/Qwen3-8B-Base
        - Qwen/Qwen3-30B-A3B-Base

pytorch_base_model:
    tp:
        - Qwen/Qwen3-8B-Base
        - Qwen/Qwen3-30B-A3B-Base

turbomind_quantization:
    no_awq:
        - meta-llama/Meta-Llama-3.1-70B-Instruct
        - internlm/internlm3-8b-instruct
        - Qwen/Qwen3-30B-A3B
        - Qwen/Qwen3-235B-A22B-Thinking-2507
        - Qwen/Qwen3-235B-A22B-Thinking-2507-FP8
        - Qwen/Qwen3-32B-FP8
        - Qwen/Qwen3-30B-A3B-FP8
        - Qwen/Qwen3-30B-A3B-Base
        - Qwen/Qwen1.5-MoE-A2.7B-Chat
        - Qwen/Qwen2.5-VL-7B-Instruct
        - Qwen/Qwen2.5-VL-32B-Instruct
        - OpenGVLab/InternVL3_5-30B-A3B
        - deepseek-ai/DeepSeek-V2-Lite-Chat
        - openai/gpt-oss-120b
        - openai/gpt-oss-20b
        - microsoft/Phi-3-mini-4k-instruct
        - THUDM/glm-4v-9b
        - THUDM/glm-4-9b-chat

    gptq:
        - empty
    no_kvint4:
        - meta-llama/Llama-3.2-1B-Instruct
        - OpenGVLab/InternVL3-2B
        - OpenGVLab/InternVL3-8B
        - Qwen/Qwen3-0.6B
        - Qwen/Qwen3-4B
        - Qwen/Qwen3-8B
        - Qwen/Qwen3-32B-FP8
        - Qwen/Qwen3-30B-A3B
        - Qwen/Qwen3-30B-A3B-FP8
        - Qwen/Qwen3-235B-A22B-Thinking-2507
        - Qwen/Qwen3-235B-A22B-Thinking-2507-FP8
        - Qwen/Qwen2.5-VL-7B-Instruct
        - Qwen/Qwen2.5-VL-32B-Instruct
        - Qwen/Qwen1.5-MoE-A2.7B-Chat
        - Qwen/Qwen3-8B-Base
        - Qwen/Qwen3-30B-A3B-Base
        - deepseek-ai/DeepSeek-V2-Lite-Chat
        - openai/gpt-oss-120b
        - openai/gpt-oss-20b
    no_kvint8:
        - deepseek-ai/DeepSeek-V2-Chat
        - Qwen/Qwen3-235B-A22B-Thinking-2507-FP8

pytorch_quantization:
    awq:
        - meta-llama/Llama-3.2-3B-Instruct
        - meta-llama/Meta-Llama-3-8B-Instruct
        - meta-llama/Meta-Llama-3.1-8B-Instruct
        - internlm/internlm3-8b-instruct
        - Qwen/Qwen3-0.6B
        - Qwen/Qwen3-4B
        - Qwen/Qwen3-8B
    w8a8:
        - meta-llama/Llama-3.2-1B-Instruct
        - meta-llama/Meta-Llama-3-8B-Instruct
        - meta-llama/Meta-Llama-3.1-8B-Instruct
        - internlm/internlm3-8b-instruct
        - microsoft/Phi-3-mini-4k-instruct
    no_kvint4:
        - meta-llama/Llama-3.2-1B-Instruct
        - OpenGVLab/InternVL3-2B
        - OpenGVLab/InternVL3-8B
        - Qwen/Qwen3-8B-Base
        - Qwen/Qwen3-30B-A3B-Base
        - Qwen/Qwen3-0.6B
        - Qwen/Qwen3-4B
        - Qwen/Qwen3-8B
        - Qwen/Qwen3-32B-FP8
        - Qwen/Qwen3-30B-A3B
        - Qwen/Qwen3-30B-A3B-FP8
        - Qwen/Qwen3-235B-A22B-Thinking-2507
        - Qwen/Qwen3-235B-A22B-Thinking-2507-FP8
        - Qwen/Qwen3-VL-8B-Instruct
        - Qwen/Qwen3-VL-30B-A3B-Instruct
        - microsoft/Phi-3-vision-128k-instruct
        - microsoft/Phi-3.5-vision-instruct
        - zai-org/GLM-4.7-Flash
        - zai-org/GLM-5
        - Qwen/Qwen3.5-27B
        - Qwen/Qwen3.5-35B-A3B
        - Qwen/Qwen3.5-122B-A10B
        - deepseek-ai/DeepSeek-V3.1
    no_kvint8:
        - zai-org/GLM-4.7-Flash
        - zai-org/GLM-5
        - deepseek-ai/DeepSeek-V3.1
        - Qwen/Qwen3.5-27B
        - Qwen/Qwen3.5-35B-A3B
        - Qwen/Qwen3.5-122B-A10B
        - Qwen/Qwen3-235B-A22B-Thinking-2507-FP8

longtext_model:
    - Qwen/Qwen3-30B-A3B
    - Qwen/Qwen3-235B-A22B-Thinking-2507
    - zai-org/GLM-5
    - Qwen/Qwen3.5-27B
    - Qwen/Qwen3.5-35B-A3B
    - Qwen/Qwen3.5-122B-A10B

benchmark_model:
    - meta-llama/Meta-Llama-3.1-8B-Instruct
    - meta-llama/Meta-Llama-3.1-70B-Instruct
    - Qwen/Qwen3-30B-A3B
    - Qwen/Qwen3-235B-A22B-Thinking-2507
    - Qwen/Qwen2.5-72B-Instruct
    - openai/gpt-oss-120b
    - openai/gpt-oss-20b
    - unsloth/gpt-oss-20b-BF16
    - zai-org/GLM-5
    - Qwen/Qwen3.5-27B
    - Qwen/Qwen3.5-35B-A3B
    - Qwen/Qwen3.5-122B-A10B
    - google/gemma-3-27b-it

evaluate_model:
    - Qwen/Qwen3-32B-FP8
    - Qwen/Qwen3-30B-A3B
    - Qwen/Qwen3-30B-A3B-FP8
    - Qwen/Qwen3-235B-A22B-Thinking-2507
    - Qwen/Qwen3-235B-A22B-Thinking-2507-FP8
    - openai/gpt-oss-120b
    - deepseek-ai/DeepSeek-V3.1
    - zai-org/GLM-5
    - Qwen/Qwen3.5-27B
    - Qwen/Qwen3.5-35B-A3B
    - Qwen/Qwen3.5-122B-A10B

mllm_evaluate_model:
    - OpenGVLab/InternVL3_5-38B
    - Qwen/Qwen3-VL-30B-A3B-Instruct
