# HF model id: meta-llama/Llama-3.2-1B-Instruct

a100:
- model_type: chat
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    pytorch:
    - w8a8
h:
- model_type: chat
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    pytorch:
    - w8a8
'3090':
- model_type: chat
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
- model_type: chat
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
  deps:
    transformers: 4.57.6
'5080':
- model_type: chat
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
- model_type: chat
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
  deps:
    transformers: 4.57.6
