# HF model id: meta-llama/Meta-Llama-3.1-70B-Instruct
a100:
- model_type: chat
  engine_config:
    tp: 4
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - func
  - prefix_cache
  deps:
    transformers: 4.57.6

h:
- model_type: chat
  engine_config:
    tp: 4
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - func
  - prefix_cache
  quantization:
    turbomind:
    - kvint4
    - kvint8
    pytorch:
    - kvint4
    - kvint8
