# HF model id: meta-llama/Meta-Llama-3.1-70B

a100:
- model_type: base
  engine_config:
    tp: 4
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - evaluate
  interface:
    pytorch:
      suites:
      - base
    turbomind:
      suites:
      - base
  deps:
    transformers: 4.57.6
