apiVersion: v1
kind: Service
metadata:
  labels:
    app: internlm2-chat-7b
  name: internlm2-chat-7b-svc
spec:
  ports:
  - name: main
    port: 23333
    protocol: TCP
    targetPort: main
  selector:
    app: internlm2-chat-7b
  type: ClusterIP
