name: 🚀 Feature request
description: Suggest an idea for this project
title: "[Feature] "

body:
- type: markdown
  attributes:
    value: |
      We strongly appreciate you creating a PR to implement this feature [here](https://github.com/InternLM/lmdeploy/pulls)!
      If you need our help, please fill in as much of the following form as you're able to.

      **The less clear the description, the longer it will take to solve it.**
- type: textarea
  attributes:
    label: Motivation
    description: |
      A clear and concise description of the motivation of the feature.
      Ex1. It is inconvenient when \[....\].
  validations:
    required: true
- type: textarea
  attributes:
    label: Related resources
    description: |
      If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context or screenshots about the feature request here.
      If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.
