version: 2

formats: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"


sphinx:
  configuration: docs/en/conf.py


python:
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/readthedocs.txt
