ARG CANN_TAG=8.1.rc1-a3-openeuler22.03-py3.10
ARG ASCEND_HUB=swr.cn-south-1.myhuaweicloud.com/ascendhub
ARG BASE_IMAGE=${ASCEND_HUB}/cann:${CANN_TAG}

FROM ${BASE_IMAGE} AS builder

ENV LMDEPLOY_TARGET_DEVICE=ascend
WORKDIR /opt/lmdeploy
COPY . .
RUN --mount=type=cache,target=/root/.cache \
    pip config set global.index-url https://mirrors.aliyun.com/pypi/simple && \
    pip config set global.trusted-host mirrors.aliyun.com && \
    pip install --no-cache-dir -U pip build && \
    python -m build -w -o /wheels -v .

FROM ${BASE_IMAGE} AS final

RUN --mount=type=cache,target=/root/.cache \
    pip config set global.index-url  https://mirrors.aliyun.com/pypi/simple  && \
    pip config set global.trusted-host  mirrors.aliyun.com  && \
    pip install --no-cache-dir torch==2.3.1 torch-npu==2.3.1 torchvision==0.18.1

RUN --mount=type=cache,target=/wheels,from=builder,source=/wheels \
    pip install --no-cache-dir /wheels/*.whl

ENTRYPOINT []
