ARG BASE_IMAGE=openmmlab/lmdeploy:latest-cu12
ARG GDRCOPY_HOME=/usr/local/gdrcopy
ARG NVSHMEM_PREFIX=/usr/local/nvshmem

# build stage
FROM ${BASE_IMAGE} AS builder_stage

ARG CUDA_HOME=/usr/local/cuda
ARG GDRCOPY_HOME
ARG NVSHMEM_PREFIX

# GDRCopy
WORKDIR /tmp
RUN dpkg -r libgdrapi gdrcopy && \
    wget https://github.com/NVIDIA/gdrcopy/archive/refs/tags/v2.4.4.tar.gz && \
    tar -zxvf v2.4.4.tar.gz && cd gdrcopy-2.4.4 && \
    make prefix=${GDRCOPY_HOME} install -j$(nproc)

# DeepEP
RUN git clone --depth=1 https://github.com/deepseek-ai/DeepEP.git

# NVSHMEM
RUN wget https://developer.nvidia.com/downloads/assets/secure/nvshmem/nvshmem_src_3.2.5-1.txz && \
    tar xvf nvshmem_src_3.2.5-1.txz && \
    cd nvshmem_src && git apply /tmp/DeepEP/third-party/nvshmem.patch && \
    NVSHMEM_SHMEM_SUPPORT=0 \
    NVSHMEM_UCX_SUPPORT=0 \
    NVSHMEM_USE_NCCL=0 \
    NVSHMEM_MPI_SUPPORT=0 \
    NVSHMEM_IBGDA_SUPPORT=1 \
    NVSHMEM_PMIX_SUPPORT=0 \
    NVSHMEM_TIMEOUT_DEVICE_POLLING=0 \
    NVSHMEM_USE_GDRCOPY=1 \
    cmake -S . -B build/ -DCMAKE_INSTALL_PREFIX=${NVSHMEM_PREFIX} \
    -DMLX5_lib=/lib/x86_64-linux-gnu/libmlx5.so.1 && \
    cmake --build build --target install --parallel $(nproc)

# install DeepEP
RUN cd DeepEP && NVSHMEM_DIR=${NVSHMEM_PREFIX} pip install -v .

# export stage
FROM ${BASE_IMAGE} AS export_stage

ARG GDRCOPY_HOME
ARG NVSHMEM_PREFIX

COPY --from=builder_stage ${GDRCOPY_HOME} ${GDRCOPY_HOME}
COPY --from=builder_stage ${NVSHMEM_PREFIX} ${NVSHMEM_PREFIX}
COPY --from=builder_stage /opt/py3/lib/python3.10/site-packages/deep_ep/ /opt/py3/lib/python3.10/site-packages/deep_ep/
COPY --from=builder_stage /opt/py3/lib/python3.10/site-packages/deep_ep_cpp* /opt/py3/lib/python3.10/site-packages/

WORKDIR /opt
# install FlashMLA
RUN git clone --recursive --depth=1 https://github.com/deepseek-ai/FlashMLA.git && \
    cd FlashMLA && python setup.py install && \
    cd .. && rm -rf FlashMLA

# install DeepGEMM
RUN git clone --recursive --depth=1 https://github.com/deepseek-ai/DeepGEMM.git && \
    cd DeepGEMM && python setup.py install && \
    cd .. && rm -rf DeepGEMM

# set workspace
WORKDIR /opt/lmdeploy
