# HF model id: zai-org/glm-4-9b-chat

a100:
- model_type: chat
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - func
  - prefix_cache
  - quantization
  quantization:
    turbomind:
    - awq
    - kvint4
    - kvint8
    pytorch:
    - kvint4
    - kvint8
h:
- model_type: chat
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint4
    - kvint8
    pytorch:
    - kvint4
    - kvint8
