# HF model id: internlm/internlm3-8b-instruct-awq
# Normalized by autotest/tools/normalize_model_configs.py

a100:
- model_type: chat
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint4
    - kvint8
h:
- model_type: chat
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint4
    - kvint8
