# HF model id: internlm/Intern-S1-Pro

h:
- model_type: chat
  engine_config:
    dp: 16
    ep: 16
    extra:
      session-len: 65536
      max-batch-size: 128
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - evaluate
  - func
  interface:
    pytorch:
    - suites:
      - base
      - logprob
      - toolcall
      - reasoning
      extra:
        logprobs-mode: raw_logprobs
        enable-return-routed-experts: true
        tool-call-parser: qwen3
        reasoning-parser: default
    - suites:
      - anthropic
      extra:
        logprobs-mode: raw_logprobs
  gen_config:
    temperature: 0.8
    top-p: 0.95
    top-k: 50
    min-p: 0.0
- model_type: chat
  engine_config:
    tp: 16
    extra:
      session-len: 65536
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - evaluate
  - func
  interface:
    pytorch:
    - suites:
      - base
      - logprob
      - toolcall
      - reasoning
      extra:
        logprobs-mode: raw_logprobs
        enable-return-routed-experts: true
        tool-call-parser: qwen3
        reasoning-parser: default
    - suites:
      - anthropic
      extra:
        logprobs-mode: raw_logprobs
  gen_config:
    temperature: 0.8
    top-p: 0.95
    top-k: 50
    min-p: 0.0
