# HF model id: internlm/Intern-S1-Pro-BF16

ascend:
- model_type: chat
  engine_config:
    dp: 64
    ep: 64
    extra:
      rank-table-file: rank_table/rank_table_4x16.json
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
