# HF model id: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B

h:
- model_type: chat
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  interface:
    pytorch:
      suites:
      - reasoning
      extra:
        reasoning-parser: deepseek-r1
    turbomind:
      suites:
      - reasoning
      extra:
        reasoning-parser: deepseek-r1
