# HF model id: deepseek-ai/DeepSeek-V3.1
# Normalized by autotest/tools/normalize_model_configs.py

h:
- model_type: chat
  engine_config:
    tp: 8
    extra:
      session-len: 65536
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - evaluate
  - func
  gen_config:
    temperature: 0.6
