# Copyright (c) OpenMMLab. All rights reserved.
import re
import secrets

from lmdeploy.tokenizer import Tokenizer
from lmdeploy.utils import get_logger

logger = get_logger('lmdeploy')

_PLACEHOLDER_BEGIN = ''
_PLACEHOLDER_END = ''


class SpecialTokenGuard:
    """Keep special-token literals in message content from being encoded as
    special tokens.

    A chat template renders message content into the prompt string, and the tokenizer parses every special-token
    literal in that string as a special token, so a user could forge turn boundaries by typing them. Special tokens in
    the prompt are only allowed to come from the chat template itself. Before rendering, the guard replaces the
    special-token literals in the content of non-assistant messages with placeholders. After rendering, it encodes the
    prompt piece by piece: the template text is encoded as usual, while the escaped literals are encoded as plain text.

    Args:
        tokenizer (Tokenizer): The tokenizer used to encode prompts.
    """

    def __init__(self, tokenizer: Tokenizer):
        self.tokenizer = tokenizer
        self.special_tokens = self._splittable_special_tokens(tokenizer)
        self._token_index = {token: i for i, token in enumerate(self.special_tokens)}
        self._token_pattern = None
        if self.special_tokens:
            # Longer tokens first, so a token is never matched by its own prefix.
            tokens = sorted(self.special_tokens, key=len, reverse=True)
            self._token_pattern = re.compile('|'.join(map(re.escape, tokens)))

    @staticmethod
    def _splittable_special_tokens(tokenizer: Tokenizer) -> list[str]:
        tokens = tokenizer.special_tokens
        if not tokens:
            return []
        probe = tokens[0]
        special_ids = tokenizer.encode(probe, add_bos=False, add_special_tokens=False)
        try:
            plain_ids = tokenizer.encode(probe, add_bos=False, add_special_tokens=False, split_special_tokens=True)
        except TypeError:
            plain_ids = special_ids
        if plain_ids == special_ids:
            logger.warning('The tokenizer does not support `split_special_tokens`. Special-token literals in message '
                           'content will be encoded as special tokens.')
            return []
        return tokens

    def escape(self, messages: str | list[dict]) -> tuple[str | list[dict], str | None]:
        """Replace the special-token literals in message content with
        placeholders.

        Args:
            messages (str | list[dict]): A user prompt, or OpenAI-style messages. The content of assistant messages is
                kept as is, since special tokens there are generated by the model.

        Returns:
            tuple[str | list[dict], str | None]: The escaped messages, and the placeholder prefix to pass to
            :meth:`encode`. The prefix is None if nothing is escaped.
        """
        if self._token_pattern is None:
            return messages, None

        prefix = f'{_PLACEHOLDER_BEGIN}{secrets.token_hex(4)}:'
        num_escaped = 0

        def _escape(text: str) -> str:
            nonlocal num_escaped
            text, num = self._token_pattern.subn(
                lambda match: f'{prefix}{self._token_index[match.group(0)]}{_PLACEHOLDER_END}', text)
            num_escaped += num
            return text

        if isinstance(messages, str):
            messages = _escape(messages)
        else:
            escaped_messages = []
            for message in messages:
                content = message.get('content')
                if message.get('role') != 'assistant' and isinstance(content, str):
                    message = {**message, 'content': _escape(content)}
                escaped_messages.append(message)
            messages = escaped_messages

        if num_escaped == 0:
            return messages, None
        logger.warning(f'Found {num_escaped} special-token literal(s) in message content, '
                       'which will be encoded as plain text.')
        return messages, prefix

    def encode(self, prompt: str, prefix: str | None) -> tuple[str, list[int]]:
        """Encode a prompt rendered from escaped messages.

        Args:
            prompt (str): The prompt rendered by the chat template.
            prefix (str | None): The placeholder prefix returned by :meth:`escape`. If None, the prompt is encoded
                as a whole.

        Returns:
            tuple[str, list[int]]: The prompt with placeholders restored to the original literals, and its token ids.
        """
        if prefix is None:
            return prompt, self.tokenizer.encode(prompt, add_bos=True)

        pattern = re.compile(f'{re.escape(prefix)}(\\d+){_PLACEHOLDER_END}')
        # re.split with a capturing group alternates template text and token indexes.
        parts = pattern.split(prompt)
        texts = []
        input_ids = []
        for i, part in enumerate(parts):
            if i % 2 == 1:
                text = self.special_tokens[int(part)]
                ids = self.tokenizer.encode(text, add_bos=False, add_special_tokens=False, split_special_tokens=True)
            elif i == 0:
                text = part
                ids = self.tokenizer.encode(text, add_bos=True)
            else:
                text = part
                ids = self.tokenizer.encode(text, add_bos=False, add_special_tokens=False) if text else []
            texts.append(text)
            input_ids.extend(ids)
        return ''.join(texts), input_ids
