# Copyright (c) OpenMMLab. All rights reserved.
from transformers.configuration_utils import PretrainedConfig


class DeepseekV4Config(PretrainedConfig):
    model_type = 'deepseek_v4'

    def __init__(self,
                 architectures=None,
                 attention_bias=False,
                 attention_dropout=0.0,
                 bos_token_id=0,
                 eos_token_id=1,
                 hc_eps=1e-6,
                 hc_mult=4,
                 hc_sinkhorn_iters=20,
                 head_dim=512,
                 hidden_act='silu',
                 hidden_size=4096,
                 index_head_dim=128,
                 index_n_heads=64,
                 index_topk=512,
                 initializer_range=0.02,
                 max_position_embeddings=1048576,
                 moe_intermediate_size=2048,
                 n_routed_experts=256,
                 n_shared_experts=1,
                 norm_topk_prob=True,
                 num_attention_heads=64,
                 num_experts_per_tok=6,
                 num_hidden_layers=43,
                 num_hash_layers=3,
                 num_key_value_heads=1,
                 num_nextn_predict_layers=1,
                 o_groups=8,
                 o_lora_rank=1024,
                 q_lora_rank=1024,
                 qk_rope_head_dim=64,
                 quantization_config=None,
                 rms_norm_eps=1e-6,
                 rope_scaling=None,
                 rope_theta=10000,
                 routed_scaling_factor=1.5,
                 scoring_func='sqrtsoftplus',
                 sliding_window=128,
                 swiglu_limit=10.0,
                 tie_word_embeddings=False,
                 topk_method='noaux_tc',
                 torch_dtype='bfloat16',
                 use_cache=True,
                 vocab_size=129280,
                 compress_rope_theta=160000,
                 compress_ratios=None,
                 **kwargs):
        super().__init__(bos_token_id=bos_token_id,
                         eos_token_id=eos_token_id,
                         tie_word_embeddings=tie_word_embeddings,
                         torch_dtype=torch_dtype,
                         **kwargs)
        self.architectures = architectures or ['DeepseekV4ForCausalLM']
        self.attention_bias = attention_bias
        self.attention_dropout = attention_dropout
        self.hc_eps = hc_eps
        self.hc_mult = hc_mult
        self.hc_sinkhorn_iters = hc_sinkhorn_iters
        self.head_dim = head_dim
        self.hidden_act = hidden_act
        self.hidden_size = hidden_size
        self.index_head_dim = index_head_dim
        self.index_n_heads = index_n_heads
        self.index_topk = index_topk
        self.initializer_range = initializer_range
        self.max_position_embeddings = max_position_embeddings
        self.moe_intermediate_size = moe_intermediate_size
        self.n_routed_experts = n_routed_experts
        self.n_shared_experts = n_shared_experts
        self.norm_topk_prob = norm_topk_prob
        self.num_attention_heads = num_attention_heads
        self.num_experts_per_tok = num_experts_per_tok
        self.num_hidden_layers = num_hidden_layers
        self.num_hash_layers = num_hash_layers
        self.num_key_value_heads = num_key_value_heads
        self.num_nextn_predict_layers = num_nextn_predict_layers
        self.o_groups = o_groups
        self.o_lora_rank = o_lora_rank
        self.q_lora_rank = q_lora_rank
        self.qk_rope_head_dim = qk_rope_head_dim
        self.quantization_config = quantization_config
        self.rms_norm_eps = rms_norm_eps
        self.rope_scaling = rope_scaling
        self.rope_theta = rope_theta
        self.routed_scaling_factor = routed_scaling_factor
        self.scoring_func = scoring_func
        self.sliding_window = sliding_window
        self.swiglu_limit = swiglu_limit
        self.topk_method = topk_method
        self.use_cache = use_cache
        self.vocab_size = vocab_size
        self.compress_rope_theta = compress_rope_theta
        self.compress_ratios = compress_ratios or [0, 0]
