# HF model id: OpenGVLab/InternVL3-38B

a100:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  interface:
    pytorch:
      suites:
      - base
      - logprob
      - anthropic
      extra:
        logprobs-mode: raw_logprobs
    turbomind:
      suites:
      - base
      - logprob
      - anthropic
      extra:
        logprobs-mode: raw_logprobs
h:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  interface:
    pytorch:
      suites:
      - base
      - logprob
      - anthropic
      extra:
        logprobs-mode: raw_logprobs
    turbomind:
      suites:
      - base
      - logprob
      - anthropic
      extra:
        logprobs-mode: raw_logprobs
