# HF model id: OpenGVLab/InternVL3_5-8B

ascend:
- model_type: vl
  engine_config:
    tp: 2
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  deps:
    transformers: 5.6.0
