# HF model id: OpenGVLab/InternVL2-Llama3-76B-AWQ

a100:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 4
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint4
    - kvint8
  deps:
    transformers: 4.57.6
