# HF model id: OpenGVLab/InternVL3-38B

a100:
- model_type: chat
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
  deps:
    transformers: 5.6.0
- model_type: vl
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
  deps:
    transformers: 5.6.0
h:
- model_type: chat
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
  deps:
    transformers: 5.6.0
- model_type: vl
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
  deps:
    transformers: 5.6.0
