# HF model id: OpenGVLab/InternVL2_5-1B
# Normalized by autotest/tools/normalize_model_configs.py

'3090':
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    - kvint8
    pytorch:
    - awq
    - kvint8
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    - kvint8
    pytorch:
    - awq
    - kvint8
  deps:
    transformers: 4.57.6
'5080':
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    - kvint8
    pytorch:
    - awq
    - kvint8
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    - kvint8
    pytorch:
    - awq
    - kvint8
  deps:
    transformers: 4.57.6
