# HF model id: THUDM/cogvlm2-llama3-chinese-chat-19B

a100:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    pytorch:
    - kvint4
    - kvint8
h:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    pytorch:
    - kvint4
    - kvint8
