# HF model id: Qwen/Qwen3.5-35B-A3B

a100:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint8
    pytorch:
    - kvint8
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
    extra:
      reasoning-parser: qwen-qwq
      speculative-algorithm: qwen3_5_mtp
      speculative-num-draft-tokens: 4
      max-batch-size: 256
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
h:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - evaluate
  - func
  - longtext_benchmark
  - longtext_evaluate
  - mllm_evaluate
  - quantization
  quantization:
    turbomind:
    - awq
    pytorch:
    - fp8
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
    extra:
      speculative-algorithm: qwen3_5_mtp
      speculative-num-draft-tokens: 4
      max-batch-size: 256
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - evaluate
  - func
  - longtext_benchmark
  - longtext_evaluate
  - mllm_evaluate
  quantization:
    pytorch:
    - fp8
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
ascend:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 4
    extra:
      cache-block-seq-len: 128
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - evaluate
  - func
  - longtext_benchmark
  - mllm_evaluate
  - prefix_cache
  - mllm_evaluate
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
- model_type:
  - chat
  - vl
  engine_config:
    tp: 4
    extra:
      speculative-algorithm: qwen3_5_mtp
      speculative-num-draft-tokens: 4
      max-batch-size: 64
      cache-max-entry-count: 0.6
      cache-block-seq-len: 128
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - evaluate
  - func
  - longtext_benchmark
  - mllm_evaluate
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
