# HF model id: Qwen/Qwen3-235B-A22B

a100:
- model_type: chat
  engine_config:
    tp: 8
    extra:
      cache-max-entry-count: 0.6
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint8
    pytorch:
    - kvint8
ascend:
- model_type: chat
  engine_config:
    tp: 16
    extra:
      session-len: 65536
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - evaluate
  - func
  - prefix_cache
  gen_config:
    temperature: 0.6
