# HF model id: Qwen/Qwen3-1.7B

'3090':
- model_type: chat
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    pytorch:
    - awq
- model_type: chat
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    pytorch:
    - awq
  deps:
    transformers: 4.57.6
'5080':
- model_type: chat
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    pytorch:
    - awq
- model_type: chat
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    pytorch:
    - awq
  deps:
    transformers: 4.57.6
