# HF model id: Qwen/Qwen2.5-VL-32B-Instruct

a100:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint8
h:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 2
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint8
