# HF model id: Qwen/Qwen3.5-122B-A10B

h:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 4
  backends:
  - name: turbomind
    communicators:
    - nccl
    - cuda-ipc
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - evaluate
  - func
  - longtext_benchmark
  - mllm_evaluate
  - quantization
  quantization:
    turbomind:
    - awq
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
