# HF model id: Qwen/Qwen3.5-35B-A3B-FP8

h:
- model_type: chat
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - evaluate
  - func
  - longtext_benchmark
  - mllm_evaluate
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
- model_type: chat
  engine_config:
    tp: 1
    extra:
      reasoning-parser: qwen-qwq
      speculative-algorithm: qwen3_5_mtp
      speculative-num-draft-tokens: 4
      max-batch-size: 256
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - mtp_evaluate
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
- model_type: vl
  engine_config:
    tp: 1
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - benchmark
  - evaluate
  - func
  - longtext_benchmark
  - mllm_evaluate
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
- model_type: vl
  engine_config:
    tp: 1
    extra:
      reasoning-parser: qwen-qwq
      speculative-algorithm: qwen3_5_mtp
      speculative-num-draft-tokens: 4
      max-batch-size: 256
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - mtp_evaluate
  gen_config:
    temperature: 1.0
    top-k: 20
    repetition-penalty: 1.0
    top-p: 0.95
    chat-template-kwargs:
      enable_thinking: true
