# HF model id: Qwen/Qwen3-8B-Base

a100:
- model_type: base
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    - kvint8
    pytorch:
    - kvint8
h:
- model_type: base
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  - quantization
  quantization:
    turbomind:
    - awq
    - kvint8
    pytorch:
    - kvint8
