# HF model id: Qwen/Qwen2.5-VL-7B-Instruct

a100:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint8
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint8
    pytorch:
    - kvint4
    - kvint8
  deps:
    transformers: 4.57.6
h:
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
  backends:
  - name: turbomind
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    turbomind:
    - kvint8
'3090':
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    pytorch:
    - kvint4
    - kvint8
  deps:
    transformers: 4.57.6
