# HF model id: Qwen/Qwen2.5-VL-3B-Instruct

'3090':
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  deps:
    transformers: 4.57.6
'5080':
- model_type: vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  deps:
    transformers: 4.57.6
