# HF model id: Qwen/Qwen2.5-VL-3B-Instruct
# Normalized by autotest/tools/normalize_model_configs.py

'3090':
- model_type:
  - chat
  - vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    pytorch:
    - kvint4
    - kvint8
  deps:
    transformers: 4.57.6
'5080':
- model_type: vl
  engine_config:
    tp: 1
    extra:
      cache-max-entry-count: 0.5
  backends:
  - name: pytorch
    communicators:
    - nccl
  test_coverage:
  - func
  quantization:
    pytorch:
    - kvint4
    - kvint8
  deps:
    transformers: 4.57.6
