# Copyright (c) OpenMMLab. All rights reserved.
from collections.abc import Sequence

import dlinfer.ops as ext_ops
from torch import Tensor


def prefill_attention(
    query_states: Tensor,
    key_states: Tensor,
    value_states: Tensor,
    attn_output: Tensor,
    key_cache: Tensor,
    value_cache: Tensor,
    block_offsets: Tensor,
    q_seqlens: Tensor,
    kv_seqlens: Tensor,
    max_q_seq_len: int,
    max_kv_seq_len: int,
    block_size: int,
    num_q_heads: int,
    num_kv_heads: int,
    head_size_v: int,
    attn_mask: Sequence[Tensor | None],
    softmax_scale: float | None,
    is_prefill_no_cache: bool | None,
    kv_scales: Tensor | None,
    kv_zeros: Tensor | None,
    quant_bits: int | None,
    cu_seqlens_q: Tensor,
    cu_seqlens_q_cpu: Tensor,
    kv_seqlens_cpu: Tensor,
) -> Tensor:
    actual_q_seqlens_cpu = cu_seqlens_q_cpu[1:]
    if is_prefill_no_cache:
        return ext_ops.prefill_attention(
            query_states,
            key_states,
            value_states,
            key_cache,
            value_cache,
            q_seqlens,
            kv_seqlens,
            max_q_seq_len,
            num_q_heads,
            num_kv_heads,
            attn_mask,
            softmax_scale=softmax_scale,
            attn_output=attn_output,
            actual_seq_lengths_cpu=actual_q_seqlens_cpu,
        )
    else:
        return ext_ops.paged_prefill_attention(
            query_states,
            key_states,
            value_states,
            key_cache,
            value_cache,
            block_offsets,
            block_size,
            actual_q_seqlens_cpu,
            kv_seqlens_cpu,
            max_q_seq_len,
            max_kv_seq_len,
            num_q_heads,
            num_kv_heads,
            attn_mask,
            head_size_v=head_size_v,
            softmax_scale=softmax_scale,
            attn_output=attn_output,
            kv_scales=kv_scales,
            kv_zeros=kv_zeros,
            quant_bits=quant_bits,
        )


def paged_token_attention(
    q,
    k_cache,
    v_cache,
    attn_output,
    actual_q_seqlens_cpu,
    kv_seqlens_cpu,
    max_kv_seq_len,
    block_offsets,
    block_size,
    num_q_heads,
    num_kv_heads,
    head_size_v,
    softmax_scale: float | None,
    kv_scales: Tensor | None,
    kv_zeros: Tensor | None,
    quant_bits: int | None,
):
    return ext_ops.paged_decode_attention(
        q,
        k_cache,
        v_cache,
        block_offsets,
        block_size,
        actual_q_seqlens_cpu,
        kv_seqlens_cpu,
        max_kv_seq_len,
        num_q_heads,
        num_kv_heads,
        head_size_v=head_size_v,
        softmax_scale=softmax_scale,
        attn_output=attn_output,
        kv_scales=kv_scales,
        kv_zeros=kv_zeros,
        quant_bits=quant_bits,
    )


def paged_attention_fwd(
    query_states: Tensor,
    key_states: Tensor,
    value_states: Tensor,
    attn_output: Tensor,
    key_cache: Tensor,
    value_cache: Tensor,
    block_offsets: Tensor,
    q_seqlens: Tensor,
    kv_seqlens: Tensor,
    max_q_seq_len: int,
    max_kv_seq_len: int,
    is_decoding: bool,
    block_size: int,
    num_heads: int,
    num_kv_heads: int,
    v_head_size: int,
    cu_seqlens_q: Tensor,
    cu_seqlens_q_cpu: Tensor,
    kv_seqlens_cpu: Tensor,
    attn_mask: Sequence[Tensor | None] = (),
    softmax_scale: float | None = None,
    is_prefill_no_cache: bool | None = None,
    kv_scales: Tensor | None = None,
    kv_zeros: Tensor | None = None,
    quant_bits: int | None = 0,
):
    if not is_decoding:
        return prefill_attention(
            query_states,
            key_states,
            value_states,
            attn_output,
            key_cache,
            value_cache,
            block_offsets,
            q_seqlens,
            kv_seqlens,
            max_q_seq_len,
            max_kv_seq_len,
            block_size,
            num_heads,
            num_kv_heads,
            v_head_size,
            attn_mask,
            softmax_scale,
            is_prefill_no_cache,
            kv_scales=kv_scales,
            kv_zeros=kv_zeros,
            quant_bits=quant_bits,
            cu_seqlens_q=cu_seqlens_q,
            cu_seqlens_q_cpu=cu_seqlens_q_cpu,
            kv_seqlens_cpu=kv_seqlens_cpu,
        )
    else:
        return paged_token_attention(
            query_states,
            key_cache,
            value_cache,
            attn_output,
            cu_seqlens_q_cpu[1:],
            kv_seqlens_cpu,
            max_kv_seq_len,
            block_offsets,
            block_size,
            num_heads,
            num_kv_heads,
            v_head_size,
            softmax_scale=softmax_scale,
            kv_scales=kv_scales,
            kv_zeros=kv_zeros,
            quant_bits=quant_bits,
        )
