name: publish-docker-nightly

on:
  workflow_dispatch:
    inputs:
      repo_ref:
        required: false
        description: 'Set branch or tag or commit id. Default is ""'
        type: string
        default: 'main'
  schedule:
    - cron:  '00 8 * * 0-4'

env:
  TAG: "openmmlab/lmdeploy:latest-cu12.8"

jobs:
  publish_inner_docker_image:
    runs-on: image-sync-inner
    env:
      INNER_TAG: "registry.h.pjlab.org.cn/ailab-puyu-puyu_gpu/lmdeploy:nightly-cu12.8"
    steps:
      - name: Pull and push to inner
        run: |
          docker pull ${{ env.TAG }}
          docker login registry.h.pjlab.org.cn -p ${{ secrets.CLUSTER_DOCKERHUB_TOKEN }} -u ${{ secrets.CLUSTER_DOCKERHUB_USERNAME }}
          docker tag ${{ env.TAG }} ${{ env.INNER_TAG }}
          docker push ${{ env.INNER_TAG }}
